sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7-dev'
- 'pypy'
- 'pypy3'
addons:
  apt_packages: [ pandoc ]
branches:
  only:
  - master
  - doc/sphinxdoc
  - 0.11
env:
  global:
    - DEPLOY_BRANCHES: "'master 0.11'"
    - DEPLOY_PYTHONS: "'2.7 3.6'"
    - PYB_ARGS: "'-v -X install_dependencies analyze install'"
    - TWINE_USERNAME: "pybuilder_travis2"
    - secure: "MLdQVfB8Xj+8oHzOCrAGTRT2SIL2+daepxlhmPPj5KJ8Zo8Fm2zPkiiTpGsklkVN3pXWGKN8kAu71/yCS2KYR+Ui1WTAg9zKMMDMY2AXuMRDlp4y82ZIrIoprhzq/bjfmqpvSYP9Ppe39HULx9sy8hFuE328NylWXoedz6FgKLU="
before_script:
- pip install coveralls
script:
- "./travis_build.sh"
after_success:
- coveralls --verbose
